/**
 * Per-client image resolution.
 *
 * Drop images in clients/<slug>/images/ and reference them by filename in
 * site.config.mjs or content frontmatter. Returns Astro ImageMetadata so
 * every image goes through <Image /> (WebP + width/height, no CLS).
 * Returns null when the client has no such image — every component that uses
 * images must render fine without them, because early demos often have none.
 */
// Generated by the `glazeos-client-images` Vite plugin in astro.config.mjs:
// { 'job-1.webp': ImageMetadata, ... } for the active CLIENT only.
import all from 'virtual:client-images';

export function clientImage(name) {
  if (!name) return null;
  return all[name] ?? null;
}

export function clientImages(names = []) {
  return names.map((n) => ({ ...n, asset: clientImage(n.src) })).filter((n) => n.asset);
}
